name: ".NET Back-End: Build - Test - Deploy"

on:
  push:
    branches: [ master ]
    paths: [ "src/back/**", ".github/workflows/dotnet.yml" ]

jobs:
  build:
    name: .NET Back-End CI/CD
    defaults:
      run:
        working-directory: ./src/back/ICT-151/
    runs-on: ubuntu-latest

    steps:
    #- name: Cache
    #- uses: actions/cache@v2.1.3
    #  with:
    #    # A list of files, directories, and wildcard patterns to cache and restore
    #    path: '/src/back/ICT-151/'
    #    # An explicit key for restoring and saving the cache
    #   key: ${{ runner.os }}-backend
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      # ${{ env.GITHUB_WORKSPACE }}/src/back/ICT-151/ICT-151.sln
      run: dotnet test --no-build --verbosity normal
    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ICT-151-Back'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c1d904916e184b4397136612b3161bc3 }}
        package: ${{env.DOTNET_ROOT}}/myapp
