name: .NET

on:
  push:
    branches: [ master ]
    paths: [ "src", ".github/workflows/" ]
  pull_request:
    paths: [ "src", ".github/workflows/" ]
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #- name: Cache
    #- uses: actions/cache@v2.1.3
    #  with:
    #    # A list of files, directories, and wildcard patterns to cache and restore
    #    path: '/src/back/ICT-151/'
    #    # An explicit key for restoring and saving the cache
    #   key: ${{ runner.os }}-backend
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ${{ GITHUB_WORKSPACE }}/src/back/ICT-151/ICT-151.sln --no-restore
    - name: Test
      run: dotnet test ${{ GITHUB_WORKSPACE }}/src/back/ICT-151/ICT-151.sln --no-build --verbosity normal
